[Project][Tasks][Inline] Tasks and boards store added along with the …
betagouv/urbanvitaliz-django pull request #105
Opened 2022-12-26 10:49 UTC by qdanneville

Trello card -> https://trello.com/c/FY0zKS2G/1100-etq-participant-dun-projet-jacc%C3%A8de-%C3%A0-une-vue-compl%C3%A8mentaire-au-kanban-pour-synth%C3%A9tiser-les-reco

2023-01-17 13:50 UTC, glibersat requested changes

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/apps/projects/templates/projects/project/actions_inline.html
> +<script src="https://cdn.jsdelivr.net/npm/js-md5@0.7.3/src/md5.min.js"></script>
pas moyen de passer ça sur vite maintenant?

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline/status_item.html
> +                       x-on:change="handleDraftFilterChange()"
Si on est sur l'implémentation générique du Kanban, je me dis que ce serait bien de ne pas nommer les éléments non génériques (ici Draft). Peut être à passer en paramètre ou à créer une surcouche au kanban? (c'est pas urgent)

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline/status_list.html
> +    <template x-for="board in boardsFiltered">
empty state?

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline/tasks_inline.html
> +    <script src="https://cdn.jsdelivr.net/npm/js-md5@0.7.3/src/md5.min.js"></script>
idem pour vite

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +        currentlyHoveredElement: null,
rgreouper les variables en haut

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +        canAdministrate: false,
idem, regrouper en haut

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +        canManage: false,
same

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +        isSwitchtender: false,
same same, et les suivants :)

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +            const userEmail = document.getElementById("userEmail").textContent;
tu pourrais faire une méthode pour chopper un élément dans le code html et l'utiliser pluttôt que de répéter je pense

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/Tasks.js
> +        currentTaskId: null,
zou là haut :)

2023-01-17 13:50 UTC, glibersat commented on urbanvitaliz/frontend/src/js/config/statuses.js
> +export const STATUSES = {
est-ce que ça ne devrait pas être propre à chaque application qui utiliser le kanban?

2023-01-23 10:15 UTC, glibersat commented
En essayant en préprod, voici ce qu'on a dans la console:
![image](https://user-images.githubusercontent.com/262663/214014948-471f45d3-5f0e-46e2-b82e-bc7b6be6c0e0.png)

Est-ce qu'il manquerait un fichier JS ou un point d'entrée ?  @qdanneville

2023-01-23 10:34 UTC, qdanneville commented
> En essayant en préprod, voici ce qu'on a dans la console: ![image](https://user-images.githubusercontent.com/262663/214014948-471f45d3-5f0e-46e2-b82e-bc7b6be6c0e0.png)
> 
> Est-ce qu'il manquerait un fichier JS ou un point d'entrée ? @qdanneville

@glibersat, c'est bon, j'avais oublié de fix un changement de nom de variable

2023-01-24 13:35 UTC, closed without merging