Develop
betagouv/urbanvitaliz-django pull request #172
Opened 2023-09-26 09:21 UTC by qdanneville

2023-09-26 10:02 UTC, glibersat commented on urbanvitaliz/apps/projects/serializers.py
> +        print('task', task)
NOGO ! ;)

2023-09-26 10:03 UTC, glibersat requested changes
Oh les méchants prints sauvages !

2023-09-28 07:03 UTC, glibersat requested changes

2023-09-28 07:03 UTC, glibersat commented on urbanvitaliz/frontend/src/js/components/TasksInline.js
> +                    return data
je ne comprends pas : on retourne dans un premier cas true || false ; dans le second une donnée.
Vu que c'est un filtre, j'imagine qu'il s'attend à un booléen ?
(ça marche dans ce cas si data != null je suppose mais c'est par "chance")

2023-09-28 07:03 UTC, glibersat commented on urbanvitaliz/frontend/src/js/store/previewModal.js
> +            const { data } = await api.get(taskNotificationsUrl(this.projectId, this.taskId))
est-ce que les erreurs de communication avec l'API sont gérées ?

2023-09-28 07:03 UTC, glibersat commented on urbanvitaliz/frontend/src/js/store/tasksData.js
> +            this.getTopics();
getXXX est nommé comme s'il retournait une liste de choses ; or, ici, tu les calcules. J'aurais tendance à nommer ça autrement pour éviter qu'on s'aventure à faire:
`maliste = getTopics();`

2023-09-28 07:03 UTC, glibersat commented on urbanvitaliz/templates/default_site/actstream/action.html
> +                    {% if action.action_object.role == "SWITCHTENDER" or action.action_object.role == "OBSERVER" or action.action_object.role == "ADVISOR" %}
même remarque que plus haut

2023-09-28 08:28 UTC, qdanneville commented on urbanvitaliz/apps/projects/serializers.py
> +    topic = TopicSerializer(read_only=True, many=False)
On était normalement parti sur une tache -> 1 topic, mais effectivement sur le modèle on a m2m, quoi qu'il en soit, idéalement l'API devrait me renvoyer un seul topic, donc surement à calculer côté Back, je verrai avec @rmarvie lundi prochain pour faire de la meilleure manière possible

2023-09-28 10:20 UTC, rmarvie commented
on n’est pas en m2m entre task et topicon est en m2m entre project et topic--r.Le 28 sept. 2023 à 10:29, quentin danneville ***@***.***> a écrit :﻿
@qdanneville commented on this pull request.



In urbanvitaliz/apps/projects/serializers.py:
> @@ -242,6 +250,8 @@ class Meta:
 
     resource = ResourceSerializer(read_only=True, many=False)
 
+    topic = TopicSerializer(read_only=True, many=False)

On était normalement parti sur une tache -> 1 topic, mais effectivement sur le modèle on a m2m, quoi qu'il en soit, idéalement l'API devrait me renvoyer un seul topic, donc surement à calculer côté Back, je verrai avec @rmarvie lundi prochain pour faire de la meilleure manière possible

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-09-28 15:22 UTC, patiboh commented on urbanvitaliz/apps/projects/templates/projects/project/fragments/tasks_inline_kanban/tasks_inline_kanban_new_tasks_banner.html
> +                <span x-text="`${$store.tasksData.newTasks.length > 1 ? $store.tasksData.newTasks.length + ' recommandations non lues' : $store.tasksData.newTasks.length + ' recommandation non lue'}
avec une méthode pour créer du pluriel, il faudrait prendre en compte la phrase entière et non pas les mots seuls (pour bien traiter les accords, etc). Une option pourrait être d'utiliser un dictionnaire pour y stocker les textes (key -> pluriel, singulier), et une methode pour le lire... à discuter :)

2023-10-02 08:03 UTC, glibersat commented
@qdanneville hello, peux tu mettre à jour ce PR qui est en conflit stp ?

2023-10-03 18:13 UTC, glibersat commented
@qdanneville et @patiboh il y a un conflit sur cette branche après merge de la carto ; est-ce que vous pouvez regarder ? Merci

2023-10-05 08:43 UTC, qdanneville commented
<img width="689" alt="Capture d’écran 2023-10-05 à 10 42 52" src="https://github.com/betagouv/urbanvitaliz-django/assets/36731000/d49818a2-5e6c-4456-a1f2-2922bad23607">

Test passé après merge

2023-10-09 12:41 UTC, merged