WIP : Feature/kanban actions
betagouv/urbanvitaliz-django pull request #22
Opened 2022-04-19 07:57 UTC by rkalfane

WIP of the new Kanban stuff, still needs some tweaking but it should not break the current project kanban

TODO : Add an inline messaging feature in the action boards
TODO : Add messaging in the resource modal
TODO : Show hidden actions

2022-05-03 13:13 UTC, glibersat commented
Le drag'n'drop ne fonctionne pas chez moi, la zone de destination n'est pas sentie comme acceptant un élément.
Ca revient à essayer d'aller à l'adresse de l'UUID de la carte, en changeant l'URL.
(Firefox 99.0.1)

2022-05-03 22:23 UTC, rkalfane commented
Added a bunch of new things, from UI improvements to stability issues.

The last commit with the logic for reminders works in isolation (ie. reminders are rendered properly, and  the form works) but the reminders don't get updated in  the db afterwards. This could be an issue with my configuration though.

2022-05-04 13:15 UTC, glibersat requested changes
Mis à part la petite coquille, ça semble bon.
Il faudra qu'on pense à tester le JS bientôt vu qu'on commence à en avoir une quantité importante.

2022-05-04 13:15 UTC, glibersat commented on urbanvitaliz/apps/projects/templates/projects/project/actions.html
> +                                                                    data-bs-toggle="tooltip" data-bs-placement="bottom" :title="`${f.who.first_name} $f.who.last_name}`"
il manque un crochet ouvrant pour ${f.who.last_name}

2022-05-04 13:47 UTC, merged